#!/bin/bash

if [ "$(uname -s)" = "Darwin" ]; then
  mkdir -p tmp

  if [[ ! -x "$(which go)" ]]; then
    echo >&2 "vulcanizer requires an installation of Go to build."
    exit 1
  fi
  # Colorize go output, because it's minty fresh.
  go get -u github.com/rakyll/gotest
fi

# Install linter. Should be universal. Version is pinned per package recommendations.
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.44.2

script/build
