#!/bin/bash

if [ "$(uname -s)" = "Darwin" ]; then
  mkdir -p tmp

  brew bundle &> tmp/brew-bundle.log || (
      echo "Failed to brew bundle:"
      cat tmp/brew-bundle.log
  )

  if [[ ! -x "$(which go)" ]]; then
    echo >&2 "vulcanizer requires an installation of Go to build."
    exit 1
  fi
  # Colorize go output, because it's minty fresh.
  go get -u github.com/rakyll/gotest
fi

# Install linter. Should be universal. Version is pinned per package reccomendations.
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.11.2

script/build
