#!/bin/bash
set -e

./script/build

# If gotest exists, colorize the output.
if [ -f $GOBIN/gotest ]
then
     gotest -v github.com/github/vulcanizer/...
else
    go test -v github.com/github/vulcanizer/...
fi

golangci-lint -v run
